# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BELL' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BELL
  pod "Macaw", "0.9.6"
  pod 'FloatingPanel'

end
